name: CI/CD Agriculture Intelligente

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest  # Spécifique à Windows
    
    steps:
    - uses: actions/checkout@v4
    
    # Frontend
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        
    - name: Install (Client)
      working-directory: ./client
      run: npm install
      
    - name: Build (Client)
      working-directory: ./client
      run: npm run build
      
    # Backend  
    - name: Install (Server)
      working-directory: ./server
      run: npm install
      
    - name: Test (Server)
      working-directory: ./server
      run: npm test